### ISSUE TITLE
New non-local $merge syntax doesn't work for scalar values

### ISSUE THREAD

**Issue by torinmr** [gopatchy/bkl#3]
**Description**
When using the new merge syntax `$merge: [{a: 1}, b, c]` and referring to a scalar value in another stream, it resolves to `{}` instead of the scalar value. It works correctly when using the verbose $match/$path syntax or when referencing a value in the local stream.

Input:
```
nameNonLocalOldSyntax:
  $merge:
    $match:
      kind: Service
    $path: metadata.name

nameNonLocalNewSyntax:
  $merge: [{kind: Service}, metadata.name]

nameLocal: $merge:metadata.name

metadata:
  name: myservice
---
kind: Service

metadata:
  name: myservice
```

Expected output:
```
...
nameLocal: myservice
nameNonLocalNewSyntax: myservice
nameNonLocalOldSyntax: myservice
...
```

Actual output:
```
...
nameLocal: myservice
nameNonLocalNewSyntax: {}
nameNonLocalOldSyntax: myservice
...
```

**Version**
```
go	go1.21.1
path	github.com/gopatchy/bkl/cmd/bkl
mod	github.com/gopatchy/bkl	v1.0.24	h1:Sx/XwQGldJ27qWPgd8gPb5ngIVKCbF6lfKo+wWNLi5c=
dep	github.com/jessevdk/go-flags	v1.5.0	h1:1jKYvbxEjfUl0fmqTCOfonvskHHXMjBySTLW4y9LFvc=
dep	github.com/pelletier/go-toml/v2	v2.1.0	h1:FnwAJ4oYMvbT/34k9zzHuZNrhlz48GB3/s6at6/MHO4=
dep	golang.org/x/exp	v0.0.0-20231005195138-3e424a577f31	h1:9k5exFQKQglLo+RoP+4zMjOFE14P6+vyR0baDAi0Rcs=
dep	golang.org/x/sys	v0.12.0	h1:CM0HF96J0hcLAwsHPJZjfdNzs0gftsLfgKt57wWHJ0o=
dep	gopkg.in/yaml.v3	v3.0.1	h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
build	-buildmode=exe
build	-compiler=gc
build	DefaultGODEBUG=panicnil=1
build	CGO_ENABLED=1
build	CGO_CFLAGS=
build	CGO_CPPFLAGS=
build	CGO_CXXFLAGS=
build	CGO_LDFLAGS=
build	GOARCH=arm64
build	GOOS=darwin
go	go1.21.1
path	github.com/gopatchy/bkl/cmd/bklb
mod	github.com/gopatchy/bkl	v1.0.24	h1:Sx/XwQGldJ27qWPgd8gPb5ngIVKCbF6lfKo+wWNLi5c=
dep	github.com/pelletier/go-toml/v2	v2.1.0	h1:FnwAJ4oYMvbT/34k9zzHuZNrhlz48GB3/s6at6/MHO4=
dep	golang.org/x/exp	v0.0.0-20231005195138-3e424a577f31	h1:9k5exFQKQglLo+RoP+4zMjOFE14P6+vyR0baDAi0Rcs=
dep	gopkg.in/yaml.v3	v3.0.1	h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
build	-buildmode=exe
build	-compiler=gc
build	DefaultGODEBUG=panicnil=1
build	CGO_ENABLED=1
build	CGO_CFLAGS=
build	CGO_CPPFLAGS=
build	CGO_CXXFLAGS=
build	CGO_LDFLAGS=
build	GOARCH=arm64
build	GOOS=darwin
go version go1.21.1 darwin/arm6
```
